### ISSUE TITLE
 Can't find variable: Promise

### ISSUE THREAD

**Issue by Claire-Ke** [developit/greenlet#26]
`[Vue warn]: Error in mounted hook: "ReferenceError:  Can't find variable: Promise"`
I got this error when runing Safari 5.1.7,What should I do?

**Comment by mkxml** [comment]
This version of Safari doesn't support [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). You can use a [Promise polyfill](https://github.com/stefanpenner/es6-promise).

**Comment by rubencodes** [comment]
So, the caveat here is just including a Promise polyfill in your code won't help. It has to go *within* the `greenlet`'d function, correct?

**Comment by mkxml** [comment]
@rubencodes Good point, code inside the function is executing in it's own context inside a Web Worker. So you would need `Promise` to be available in your code context too.

One possible workaround is passing a Promise polyfill down to your Web Worker code via simple dependency injection:

```javascript
// Include greenlet and global Promise polyfill before this...

const resolveOnTruthy = greenlet((Promise, value) => {
  return new Promise((resolve, reject) => {
    value ? resolve() : reject('Sorry, not truthy...')
  })
})

resolveOnTruthy(Promise, 1).then(() => console.log('Resolved!'))
```

Note that the polyfill inside the worker is not needed if you are using synchronous code.

You do need the global/main polyfill anyways because `greenlet` use Promises internally.

**Comment by rubencodes** [comment]
Ah, so this would eliminate the need to duplicate the Promise implementation. Smart!

**Comment by developit** [comment]
2 other options:

```js
greenlet(async function(value) {
  importScripts('https://unpkg.com/es6-promise@4.2.4/dist/es6-promise.auto.min.js')

  return await fetch('/foo')
})
```


```js
greenlet(function(value) {
  // promise stand-in
  function callback(err, value) {setTimeout(()=>{callback[err?0:1](err || value)})}
  callback.then=r=>{callback[0]=r}
  callback.catch=r=>{callback[1]=r}


  callback(null, value ? true : false)
  return callback
})
```
