### ISSUE TITLE
Make the source code more readable (or include comments to tell what each line does)

### ISSUE THREAD

**Issue by carstenhag** [developit/greenlet#8]
as per https://news.ycombinator.com/item?id=16257469

**Comment by developit** [comment]
I love the idea of comments annotating things!

**Comment by carstenhag** [comment]
Someone already annotated it:

https://news.ycombinator.com/item?id=16258172
https://gist.github.com/zz85/25564f1910f1877c39c25ace5e5159bc

**Comment by asaaki** [comment]
But wouldn't it be more beneficial to have speaking variable names instead?
Comments can be valuable, but should focus more on the Why instead of What, therefore the code itself should be better understandable in the what part.

Unless there was a need to win in a code golfing competition, there shouldn't be a need for single letter variables anyway.

**Comment by kevzettler** [comment]
agree with @asaaki 
looking at the code in isolation:
https://gist.github.com/zz85/25564f1910f1877c39c25ace5e5159bc#file-greenlet-js-L38-L39

I have no idea what `y`,`n`,`p`,`c` are

**Comment by developit** [comment]
Yup!

**Comment by developit** [comment]
Hey @zz85 - mind if I add some of your annotations to the library itself?

**Comment by zz85** [comment]
@developit sure, go ahead with it!

the single letter variables look rather cryptic at first and could be better named, but it was also fun trying to understand what it was doing. knowing a little about promises, web workers and javascript helped too i guess :)

**Comment by developit** [comment]
Should be much more readable now.
